### ISSUE TITLE
[Bug]: Card in kanban visual bugs

### ISSUE THREAD

**Issue by dadyarri** [AppFlowy-IO/AppFlowy#1127]
### Bug Description

1. In dark mode colors are too bright (it's unreadable) (screenshot 1)
2. Status selector doesn't close when clicking outside of it (and it places above all of the other elements, so, i. e. deleting property is not accessible) (screenshot 1) (can't make a screenshot because of exception below)
3. After closing card shadow doesn't disappear, making any of interface elements inactive (screenshot 2) (see comment https://github.com/AppFlowy-IO/AppFlowy/issues/1127#issuecomment-1254651736) (persists even after restart)

### How to Reproduce

...

### Expected Behavior

...

### Operating System

Arco Linux

### AppFlowy Version(s)

main branch

### Screenshots

![image](https://user-images.githubusercontent.com/51821039/191687141-4fcb7d73-f90e-4a5d-8ae2-a8065be93e3a.png)
![image](https://user-images.githubusercontent.com/51821039/191687224-e8989c5e-dda0-4ed8-b4ee-d507911415ba.png)

**Comment by dadyarri** [comment]
While testing i've got a runtime exception:
```
flutter: Null check operator used on a null value
flutter: #0      _BoardCardState._handlePopoverBuilder (package:app_flowy/plugins/board/presentation/card/card.dart:130)
flutter: #1      _BoardCardState.build.<anonymous closure>.<anonymous closure> (package:app_flowy/plugins/board/presentation/card/card.dart:88)
flutter: #2      AppFlowyPopover.build.<anonymous closure> (package:flowy_infra_ui/src/flowy_overlay/appflowy_stype_popover.dart:41)
flutter: #3      PopoverContainerState.build (package:appflowy_popover/src/popover.dart:242)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878)
flutter: #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
flutter: #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
flutter: #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
flutter: #12     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435)
flutter: #13     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
flutter: #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
flutter: #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
flutter: #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
flutter: #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041)
flutter: #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
flutter: #31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
flutter: #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
flutter: #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
flutter: #37     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
flutter: #39     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964)
flutter: #40     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3570)
flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
flutter: #43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
flutter: #45     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667)
flutter: #46     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
flutter: #47     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378)
flutter: #48     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175)
flutter: #49     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104)
flutter: #50     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015)
flutter: #51     _invoke (dart:ui/hooks.dart:148)
flutter: #52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318)
flutter: #53     _drawFrame (dart:ui/hooks.dart:115)
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by appflowy** [comment]
@dadyarri I fixed it. Will merge after all the CI checks pass.
