### ISSUE TITLE
[Bug]:  Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so'

### ISSUE THREAD

**Issue by VladimirCores** [AppFlowy-IO/AppFlowy#1222]
### Bug Description

Running: `./app_flowy` results in error:

```
~/.../AppFlowy$ ./app_flowy 

(app_flowy:66328): dbind-WARNING **: 12:10:28.514: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(app_flowy:66328): Gtk-WARNING **: 12:10:28.538: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/vladimir/Documents/Programs/AppFlowy/lib/libdart_ffi.so)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:26)
#3      _dl (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:13)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:12)
#9      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#10     InitRustSDKTask.initialize (package:app_flowy/startup/tasks/rust_sdk.dart:12)
<asynchronous suspension>
#11     AppLauncher.launch (package:app_flowy/startup/startup.dart:99)
<asynchronous suspension>
```

### How to Reproduce

1. Download latest version from GH
2. Extract to folder
3. run `./app_flowy`

### Expected Behavior

App runs

### Operating System

Deepin 20.7 - Linux cores 5.15.45-amd64-desktop

### AppFlowy Version(s)

1.0.0

### Screenshots

![image](https://user-images.githubusercontent.com/442111/193781483-89e403da-6edb-435c-9ba9-31e0180fde1f.png)

**Comment by richardshiue** [comment]
I could be wrong, but seems like your glibc version is too old or not found at all. To find your glibc version, enter `ldd --version` in a terminal. Also check out <https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/mac-windows-linux-packages/installing-on-linux>.

**Comment by rileyhawk1417** [comment]
> I could be wrong, but seems like your glibc version is too old or not found at all. To find your glibc version, enter `ldd --version` in a terminal. Also check out https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/mac-windows-linux-packages/installing-on-linux.

I think it's an issue for Ubuntu related Distro's particularly 20.04 versions. Would need to look into the install requirements for Ubuntu 20.04 distro's.

**Comment by VladimirCores** [comment]
`ldd --version`:
```
ldd (Debian GLIBC 2.28.19-1+dde) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by richardshiue** [comment]
Sorry for the late reply, but I guess there's your problem. You would need to install a newer version of glibc

**Comment by Cyber-Syntax** [comment]
I was running the application comfortably before and it was working fine with the older version. Now even with version "Ubuntu GLIBC 2.35-0ubuntu3.1" I get error like this:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 
Invalid argument(s): 
Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: 
cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _set_stream_port (package:appflowy_backend/ffi.dart)
#5      set_stream_port (package:appflowy_backend/ffi.dart)
#6      FlowySDK.init (package:appflowy_backend/appflowy_backend.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:24)
<asynchronous suspension>
#8      AppLauncher.launch (package:app_flowy/startup/startup.dart:124)
<asynchronous suspension>
#9      FlowyRunner.run (package:app_flowy/startup/startup.dart:64)
<asynchronous suspension>
#10     main (package:app_flowy/main.dart:25)
<asynchronous suspension>
```
