### ISSUE TITLE
[Bug] Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Cyber-Syntax** [AppFlowy-IO/AppFlowy#1932]
### Bug Description

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _set_stream_port (package:appflowy_backend/ffi.dart)
#5      set_stream_port (package:appflowy_backend/ffi.dart)
#6      FlowySDK.init (package:appflowy_backend/appflowy_backend.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:24)
<asynchronous suspension>
#8      AppLauncher.launch (package:app_flowy/startup/startup.dart:124)
<asynchronous suspension>
#9      FlowyRunner.run (package:app_flowy/startup/startup.dart:64)
<asynchronous suspension>
#10     main (package:app_flowy/main.dart:25)
<asynchronous suspension>
(appflowy:61624): GLib-GObject-WARNING **: 14:09:41.190: ../../../gobject/gsignal.c:2765: instance '0xaa71b0' has no handler with id '177'
```

App opened with gray screen.

### How to Reproduce

I don't know, I just installed it from terminal with deb package.

### Expected Behavior

opening the application

### Operating System

Pop-OS 22.04 LTS.

### AppFlowy Version(s)

0.1.0

**Comment by rileyhawk1417** [comment]
@Cyber-Syntax what Linux distro are you running?

**Comment by Cyber-Syntax** [comment]
Pop-OS LTS.

**Comment by rileyhawk1417** [comment]
You would need to install openssl, you can find information about it [here](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux)

**Comment by Cyber-Syntax** [comment]
@rileyhawk1417 Thank you.
`# Ubuntu & PopOS
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb`
Solved my problem.
