### ISSUE TITLE
Gray screen on pop os

### ISSUE THREAD

**Issue by KelvinJPS** [AppFlowy-IO/AppFlowy#2358]
### Bug Description

Gray Screen when opening the app for the first time.

### How to Reproduce

1. Download the deb file from releases
2. install it
3.  Open the app 

### Expected Behavior

That the app would render the ui

### Operating System

pop os 22.04

### AppFlowy Version(s)

0.1.3

### Screenshots

![image](https://user-images.githubusercontent.com/75276742/234453503-6ec29e13-9e54-471b-8e4d-62f3aff8992c.png)

**Comment by athomson0** [comment]
Same issue on on Ubuntu 22.04 here.

Log output:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _invoke_log (package:appflowy_backend/ffi.dart)
#5      log (package:appflowy_backend/ffi.dart)
#6      Log.error (package:appflowy_backend/log.dart:61)
#7      main.<anonymous closure> (package:appflowy/main.dart:27)
#8      PlatformDispatcher._dispatchError (dart:ui/platform_dispatcher.dart:1174)
#9      _onError (dart:ui/hooks.dart:117)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _set_stream_port (package:appflowy_backend/ffi.dart)
#5      set_stream_port (package:appflowy_backend/ffi.dart)
#6      FlowySDK.init (package:appflowy_backend/appflowy_backend.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:appflowy/startup/tasks/rust_sdk.dart:25)
<asynchronous suspension>
#8      AppLauncher.launch (package:appflowy/startup/startup.dart:124)
<asynchronous suspension>
#9      FlowyRunner.run (package:appflowy/startup/startup.dart:64)
<asynchronous suspension>
#10     main (package:appflowy/main.dart:36)
<asynchronous suspension>
```

The shared library `libssl.so.1.1` is missing. I fixed it by:

1. Download `libssl1.1_1.1.1f-1ubuntu2_amd64.deb` from the Ubuntu archive:

`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb`

2. Install it

`sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb`

3. Restart AppFlowy

**Comment by annieappflowy** [comment]
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
