### ISSUE TITLE
[Bug] msg: invalid JWT: unable to parse or verify signature, token is expired

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#4496]
### Bug Description

```
Reloaded 1 of 4296 libraries in 491ms (compile: 43 ms, reload: 136 ms, reassemble: 299 ms).
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ #0   Log.error (package:appflowy_backend/log.dart:80:26)<…>
flutter: \^[[38;5;196m│ #1   new SettingsUserViewBloc.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appflowy/workspace/application/user/settings_user_bloc.dart:34:28)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ msg: invalid JWT: unable to parse or verify signature, token is expired by 52h16m2s<…>
flutter: \^[[38;5;196m│ ⛔ <…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ #0   Log.error (package:appflowy_backend/log.dart:80:26)<…>
flutter: \^[[38;5;196m│ #1   new SettingsUserViewBloc.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appflowy/workspace/application/user/settings_user_bloc.dart:34:28)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ msg: invalid JWT: unable to parse or verify signature, token is expired by 52h16m18s<…>
flutter: \^[[38;5;196m│ ⛔ <…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
```

### How to Reproduce

- sign in on mobile
- try to update the user name

### Expected Behavior

- no errors

### Operating System

iOS

### AppFlowy Version(s)

0.4.3

**Comment by annieappflowy** [comment]
Fixed
