### ISSUE TITLE
[Bug] Cursor sometimes jumps to top line when inputting Japanese text

### ISSUE THREAD

**Issue by negiboudu** [AppFlowy-IO/AppFlowy#471]
**Describe the bug**
In Japanese text (kana) input mode, writing some text, sometimes suddenly cursor jumps to top line.
At that time, many errors appear in the console log like this:

```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   Log.error (package:flowy_sdk/log.dart:38:24)
package:flowy_sdk/log.dart:38
flutter: │ #1   DocumentBloc._composeDelta.<anonymous closure> (package:app_flowy/workspace/application/doc/doc_bloc.dart:120:13)
package:app_flowy/…/doc/doc_bloc.dart:120
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ Receive : insert⟨ いｎんｓ⏎ ⟩
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   Log.error (package:flowy_sdk/log.dart:38:24)
package:flowy_sdk/log.dart:38
flutter: │ #1   DocumentBloc._composeDelta.<anonymous closure> (package:app_flowy/workspace/application/doc/doc_bloc.dart:121:13)
package:app_flowy/…/doc/doc_bloc.dart:121
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ Expected : insert⟨ いんｓ⏎ ⟩
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**To Reproduce**
1. Change the input mode to Japanese text.
2. Keep typing any text.

**Screenshots**
<img width="1439" alt="screenshot 2022-04-30 4 07 33" src="https://user-images.githubusercontent.com/2309728/166040812-e0cbd331-14c7-4bc1-bd81-08fdfbab7423.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6.5
 - Browser: chrome
 - Version: 100.0.4896.127

**Additional context**
Maybe, this issue's cause is event called each KeyDown.
In Japanese text input mode, the flow is as follows:
input -> convert -> decision
It appears that Event is called each "input", but perhaps should be called after "decision".

**Comment by negiboudu** [comment]
I reproduced this issue.
1. Change the input mode to Japanese text.
2. Input any text. In this example "あいうお".
3. Press Delete key.
4. Input any text. In this example "え".
-> Cursor jumped to beginning point, and the previously entered strings is entered together.

![reproduced](https://user-images.githubusercontent.com/2309728/166247430-bef92faf-0942-498d-966b-4c1eb6e7938e.gif)

**Comment by negiboudu** [comment]
I confirmed that this issue was fixed in the latest version.
