### ISSUE TITLE
[Bug] A problem with input

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/AppFlowy#4763]
### Bug Description

[   +2 ms] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 14..20: 6
[        ] #0      RangeError.checkValidRange (dart:core/errors.dart:364:9)
[        ] #1      _StringBase.substring (dart:core-patch/string_patch.dart:413:27)
[        ] #2      _OpIterator.next (package:appflowy_editor/src/core/document/text_delta.dart:591:23)
[        ] #3      Delta.compose (package:appflowy_editor/src/core/document/text_delta.dart:277:33)
[        ] #4      TextTransaction.compose.<anonymous closure> (package:appflowy_editor/src/core/transform/transaction.dart:569:59)
[        ] #5      ListBase.fold (dart:collection/list.dart:202:22)
[        ] #6      TextTransaction.compose (package:appflowy_editor/src/core/transform/transaction.dart:569:22)
[        ] #7      Transaction.operations (package:appflowy_editor/src/core/transform/transaction.dart:23:7)
[        ] #8      EditorState.apply (package:appflowy_editor/src/editor_state.dart:286:41)
[        ] #9      onInsert (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_on_insert_impl.dart:110:22)
[        ] <asynchronous suspension>
[        ] #10     KeyboardServiceWidgetState.initState.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/keyboard_service_widget.dart:65:38)
[        ] <asynchronous suspension>
[        ] #11     NonDeltaTextInputService.apply (package:appflowy_editor/src/editor/editor_component/service/ime/non_delta_input_service.dart:49:9)
[        ] <asynchronous suspension>
[   +1 ms] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 14..20: 6
[        ] #0      RangeError.checkValidRange (dart:core/errors.dart:364:9)
[        ] #1      _StringBase.substring (dart:core-patch/string_patch.dart:413:27)
[        ] #2      _OpIterator.next (package:appflowy_editor/src/core/document/text_delta.dart:591:23)
[        ] #3      Delta.compose (package:appflowy_editor/src/core/document/text_delta.dart:277:33)
[        ] #4      TextTransaction.compose.<anonymous closure> (package:appflowy_editor/src/core/transform/transaction.dart:569:59)
[        ] #5      ListBase.fold (dart:collection/list.dart:202:22)
[        ] #6      TextTransaction.compose (package:appflowy_editor/src/core/transform/transaction.dart:569:22)
[        ] #7      Transaction.operations (package:appflowy_editor/src/core/transform/transaction.dart:23:7)
[        ] #8      EditorState.apply (package:appflowy_editor/src/editor_state.dart:286:41)
[        ] #9      onInsert (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_on_insert_impl.dart:110:22)
[        ] <asynchronous suspension>
[        ] #10     KeyboardServiceWidgetState.initState.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/keyboard_service_widget.dart:65:38)
[        ] <asynchronous suspension>
[        ] #11     NonDeltaTextInputService.apply (package:appflowy_editor/src/editor/editor_component/service/ime/non_delta_input_service.dart:49:9)
[        ] <asynchronous suspension>

https://github.com/AppFlowy-IO/AppFlowy/assets/4517301/9f385462-3055-440f-9894-f7c117a2cc97

### How to Reproduce

After pressing the video operation, the editor reports an error and cannot continue typing.

### Expected Behavior

The editor is normal

### Operating System

desktop

### AppFlowy Version(s)

main

**Comment by q200892907** [comment]
@LucasXu0 demo{demo}{demo}->demo{demo}\_{demo}->demo\_{demo}\_{demo}

**Comment by q200892907** [comment]
After certain operations, the editor will enter a stuck state. @LucasXu0
