### ISSUE TITLE
[Bug]  There is only a blank page when opening appflowy.

### ISSUE THREAD

**Issue by Javier-Huang** [AppFlowy-IO/AppFlowy#5117]
### Bug Description

There is only a blank page when opening appflowy.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/88572822/0f483710-5dc0-4e4f-88f4-b9d9ff56306d)

The Log is below: 
```
(AppFlowy:137742): GLib-GObject-CRITICAL **: 09:14:55.191: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(AppFlowy:137742): dbind-WARNING **: 09:14:55.262: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.747: the GVariant format string 'v' has a type of 'v' but the given value has a type of 's'

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.747: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.747: g_variant_dict_insert_value: assertion 'value != NULL' failed

** (AppFlowy:137742): CRITICAL **: 09:14:55.747: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.747: the GVariant format string 'v' has a type of 'v' but the given value has a type of 'b'

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.747: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.747: g_variant_dict_insert_value: assertion 'value != NULL' failed

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.748: the GVariant format string 'v' has a type of 'v' but the given value has a type of 's'

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.748: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.748: g_variant_dict_insert_value: assertion 'value != NULL' failed

** (AppFlowy:137742): CRITICAL **: 09:14:55.748: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.748: the GVariant format string 'v' has a type of 'v' but the given value has a type of 'd'

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.748: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(AppFlowy:137742): GLib-CRITICAL **: 09:14:55.748: g_variant_dict_insert_value: assertion 'value != NULL' failed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_AppFloF0BKNl/lib/libdart_ffi.so)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _invoke_rust_log (package:appflowy_backend/ffi.dart)
#5      rust_log (package:appflowy_backend/ffi.dart)
#6      Log.info (package:appflowy_backend/log.dart:29)
#7      _resolveCloudDeps (package:appflowy/startup/deps_resolver.dart:63)
<asynchronous suspension>
#8      DependencyResolver.resolve (package:appflowy/startup/deps_resolver.dart:53)
<asynchronous suspension>
#9      initGetIt (package:appflowy/startup/startup.dart:179)
<asynchronous suspension>
#10     FlowyRunner.run (package:appflowy/startup/startup.dart:98)
<asynchronous suspension>
#11     runAppFlowy (package:appflowy/startup/startup.dart:33)
<asynchronous suspension>
#12     main (package:appflowy/main.dart:8)
```

### How to Reproduce

My OS System
```
[Version] 
SystemName=Deepin
SystemName[zh_CN]=深度操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Community
EditionName[zh_CN]=社区版
MajorVersion=20
MinorVersion=20.9
OsBuild=11038.007
```

Run Appimage and get this error

### Expected Behavior

can run on deepin linux platform.

### Operating System

Deepin 20.9

### AppFlowy Version(s)

AppFlowy-0.5.4-linux-x86_64

**Comment by LucasXu0** [comment]
>  /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_AppFloF0BKNl/lib/libdart_ffi.so)

@Javier-Huang You can upgrade libstdc++ and try launching it again.

```shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt upgrade libstdc++6
```

**Comment by Javier-Huang** [comment]
I'm afraid I can't upgrade libc so simply and crudely, because there are a lot of basic services linked to this version, and I think you should be compatible with your build package so that it can be compatible with lower versions of libc.

**Comment by LucasXu0** [comment]
I'm not sure if it will replace your existing libstdc++ libraries. Can you post the output from this command?

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep -i glib
```

**Comment by Javier-Huang** [comment]
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.14
GLIBC_2.18
GLIBC_2.16
GLIBC_2.17
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by LucasXu0** [comment]
Based on your output, I believe you can install GLIBCXX_3.4.26 without affecting your existing glibc++ libraries.

**Comment by Javier-Huang** [comment]
I try to build appflowy source in my pc, and get this error, not any idea to it.
```
 ~/project1/AppFlowy/frontend  main  cargo make --profile production-linux-x86_64 appflowy                                                                                                 ok 

[cargo-make] INFO - cargo make 0.37.11
[cargo-make] INFO - Project: dart-ffi
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: appflowy
[cargo-make] INFO - Profile: production-linux-x86_64
[cargo-make] INFO - Execute Command: "cargo" "make" "--disable-check-for-updates" "--no-on-error" "--loglevel=info" "--profile=production-linux-x86_64" "--makefile" "/home/hjf/project1/AppFlowy/frontend/Makefile.toml" "appflowy"
[cargo-make][1] INFO - Project: dart-ffi
[cargo-make][1] INFO - Build File: /home/hjf/project1/AppFlowy/frontend/Makefile.toml
[cargo-make][1] INFO - Task: appflowy
[cargo-make][1] INFO - Profile: production-linux-x86_64
[cargo-make][1] INFO - Running Task: legacy-migration
[cargo-make][1] INFO - Running Task: echo_env
-------- Env Parameters --------
CRATE_TYPE: cdylib
BUILD_FLAG: release
TARGET_OS: linux
RUST_COMPILE_TARGET: x86_64-unknown-linux-gnu
FEATURES: dart,rev-sqlite
PRODUCT_EXT:
APP_ENVIRONMENT: production
BUILD_ARCHS:
BUILD_VERSION:
/home/hjf/.pub-cache/bin/protoc-gen-dart
[cargo-make][1] INFO - Skipping Task: install_flutter_protobuf 
[cargo-make][1] INFO - Skipping Task: env_check 
[cargo-make][1] INFO - Running Task: setup-crate-type
[cargo-make][1] INFO - Running Task: set-app-version
APP_VERSION: 0.5.5 
[cargo-make][1] INFO - Running Task: sdk-release-build
error: failed to parse manifest at `/home/hjf/project1/AppFlowy/frontend/rust-lib/Cargo.toml`

Caused by:
  feature `named-profiles` is required

consider adding `cargo-features = ["named-profiles"]` to the manifest
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: restore-crate-type
[cargo-make] ERROR - Task error detected, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by LucasXu0** [comment]
@Javier-Huang Our application requires `GLIBCXX_3.4.26`. Please install this version and try again. I'll close this issue for now, but feel free to reopen it if the problem persists after installing `GLIBCXX_3.4.26`.
