### ISSUE TITLE
[Bug] 0.6.4 - Linux - Import Data Cannot Browse Folder 

### ISSUE THREAD

**Issue by gioandtonic** [AppFlowy-IO/AppFlowy#5784]
### Bug Description

When I go to Settings -> Manage Data -> Import Data -> Browse File, it doesn't open the folder selection dialog.
![Screenshot from 2024-07-22 09-47-33](https://github.com/user-attachments/assets/181e665f-32d0-4d00-9fd3-86f1b90a7dcd)

### How to Reproduce

Have AppFlowy 0.6.3 or 0.6.4 on a Linux machine and go to:

Settings -> Manage Data -> Import Data -> Browse File

### Expected Behavior

It should allow to select a folder to import the data.

### Operating System

Ubuntu 24.04 LTS

### AppFlowy Version(s)

0.6.3, 0.6.4

### Screenshots

![Screenshot from 2024-07-22 09-47-33](https://github.com/user-attachments/assets/27d4d9e9-4845-4f12-b2f3-12b950ef9067)

**Comment by gorghino** [comment]
Confirmed on 0.6.6
Ubuntu 22.04.4 LTS x86_64
GNOME 42.9 - Mutter

**Comment by berkes** [comment]
The same error, referencing the same line in lib.rs, appears when using any of the import buttons under the modal that opens at the `+` button, then import, at a workspace. 

![image](https://github.com/user-attachments/assets/6b6cc1aa-ee3c-4a67-998e-88a678aac4cd)

```
  2024-08-29 10:53:52 ERROR dart_ffi: [Flutter]: Uncaught platform error
    at dart-ffi/src/lib.rs:245

{"msg":"[Flutter]: Uncaught platform error","time":"08-29 10:53:52","target":"dart_ffi"}
```

**Comment by berkes** [comment]
Version 0.7.0 still has the issue.

And it comes with more detailed errors!

```
  2024-10-04 12:15:48 ERROR dart_ffi: [Flutter]: Uncaught platform error
StackTrace:
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/linux/file_picker_linux.dart:127)
<asynchronous suspension>
#2      FilePickerLinux.pickFiles (package:file_picker/src/linux/file_picker_linux.dart:29)
<asynchronous suspension>
#3      FilePicker.pickFiles (package:flowy_infra/file_picker/file_picker_impl.dart:25)
<asynchronous suspension>
#4      _ImportPanelState._importFile (package:appflowy/workspace/presentation/home/menu/sidebar/import/import_panel.dart:143)
<asynchronous suspension>
#5      _ImportPanelState.build.<anonymous closure>.<anonymous closure> (package:appflowy/workspace/presentation/home/menu/sidebar/import/import_panel.dart:115)
<asynchronous suspension>

    at dart-ffi/src/lib.rs:291
  ```

**Comment by SirRujak** [comment]
I think I may have found the solution to this, or at the very least the problem. I run KDE on EndeavourOS, based on Arch with very few changes, and specifically I was missing the kdialog package. Took a bit of looking but found [this documentation](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ#q-when-using-file_picker-on-macos-or-linux-the-dialog-does-not-always-get-in-focus-so-there-is-an-extra-click-to-first-make-the-dialog-in-focus-before-you-can-actually-choose-a-file-can-you-make-the-dialog-focus-automatically-or-provide-a-better-user-experience--ux-in-general) that explains that the dart file_picker library executes shell comands to qarma, zenity, or kdialog to create a file picker.

As a short term solution users can install garma, zenity, or kdialog to get the picker working. As a long term solution it may be better to move to the official Google [file_selector](https://pub.dev/packages/file_selector) as mentioned in the above linked documentation. I will go ahead and mention this in the other closed issue as well in case others end up there first.

**Comment by annieappflowy** [comment]
Thank you,  @podcherklife ,  for the info and the effort to find the root cause.
Since export is not a feature that would make the Snap application unusable, it seems more beneficial to make snap available than removing it completely. We'll see how to notify the snap users about this filepicker issue.
