### ISSUE TITLE
mac m1 flutter run not work?

### ISSUE THREAD

**Issue by ljshwyykl** [AppFlowy-IO/appflowy#77]
**Describe the bug**

flutter run

```
 	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in
    	resolve_dependencies'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    	from /usr/local/bin/pod:23:in `load'
    	from /usr/local/bin/pod:23:in `<main>'
```

vscode 
Go to the Run and Debug tab and then click the run button.

![image](https://user-images.githubusercontent.com/73726782/142886567-36abd86c-559c-493f-b719-c50b011e98f8.png)

**Comment by deicon** [comment]
Can you provide the output of 

flutter doctor -v 

please

**Comment by ljshwyykl** [comment]
![image](https://user-images.githubusercontent.com/73726782/142969115-d04956d0-3ae1-444f-9335-2b2d608699ea.png)

**Comment by ljshwyykl** [comment]
```
https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1  
```

it is done
